database:
  host: localhost
  port: 3306
  user: chat_user
  password: chat_password
  dbname: chat_app
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

server:
  port: 8080
  mode: debug

logging:
  level: info
  format: json
